### ISSUE TITLE
Upstream: `ERROR: Can not create file with auto name`

### ISSUE THREAD

**Issue by xfzv** [hankertrix/augment-command.yazi#11]
I've just met the following error when trying to extract an archive:

![Image](https://github.com/user-attachments/assets/5e515afa-024e-4a80-b184-3863929eda16)

Using latest commit @ https://github.com/hankertrix/augment-command.yazi/commit/225c06255573ca465ab81afef6f83cd94d0b9093

Extracting archives usually works fine here so I thought I would open an issue.

Here's the zip file: [Aegisub-3.4.2-portable.zip](https://github.com/TypesettingTools/Aegisub/releases/download/v3.4.2/Aegisub-3.4.2-portable.zip)

```toml
# ~/.config/yazi/yazi.toml
extract = [
  { run = 'ya pub augmented-extract --list "$@"', desc = "Extract here" },
]

# ~/.config/yazi/keymap.toml
[[manager.prepend_keymap]]
on = ["l"]
run = "plugin augment-command --args='enter --no-skip'"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = ["<Right>"]
run = "plugin augment-command --args='enter --no-skip'"
desc = "Enter the child directory, or open the file"
```

Also occurs without `--no-skip`.

Edit:

```console
% unzip "/tmp/Aegisub-3.4.2-portable.zip"
```

works fine.
