### ISSUE TITLE
`smooth_scrolling` not working

### ISSUE THREAD

**Issue by xfzv** [hankertrix/augment-command.yazi#12]
I'd like to try the new `smooth_scrolling` feature introduced with https://github.com/hankertrix/augment-command.yazi/commit/a6464dd45979f40d0ee200e3ea5bc9cebcc0d3ef but I can't get it to work for some reason.

```console
% yazi -V
Yazi 25.2.26 (20c99c6a 2025-02-26)

% kitty -v
kitty 0.39.1 created by Kovid Goyal

% lsd --tree --icon=never ~/.config/yazi
yazi
├── plugins
│   └── augment-command.yazi
│       └── main.lua
├── init.lua
└── keymap.toml

% rg "smooth_scrolling" ~/.config/yazi/plugins/augment-command.yazi/main.lua
64:---@field smooth_scrolling boolean Whether to smoothly scroll or not
140:	smooth_scrolling = false,
3396:	if config.smooth_scrolling then
3610:	if not config.smooth_scrolling then execute_parent_arrow(args) end
```

- `init.lua`:

```lua
require("augment-command"):setup({
  smooth_scrolling = true,
  wraparound_file_navigation = true,
})
```

- `keymap.toml`:

```toml
[[manager.prepend_keymap]]
on = "k"
run = "plugin augment-command -- arrow -1"
desc = "Move cursor up"

[[manager.prepend_keymap]]
on = "<Up>"
run = "plugin augment-command -- arrow -1"
desc = "Move cursor up"

[[manager.prepend_keymap]]
on = "j"
run = "plugin augment-command -- arrow 1"
desc = "Move cursor down"

[[manager.prepend_keymap]]
on = "<Down>"
run = "plugin augment-command -- arrow 1"
desc = "Move cursor down"
```

---

```lua
wraparound_file_navigation = true,
```

works just fine, but with either

```lua
smooth_scrolling = true
-- or
smooth_scrolling = false
```

it behaves just like regular `arrow 1` and `arrow -1`.

Any idea?
