### ISSUE TITLE
`create` no longer working with yazi v25.4.8

### ISSUE THREAD

**Issue by xfzv** [hankertrix/augment-command.yazi#13]
Using https://github.com/hankertrix/augment-command.yazi/commit/269e3cf9ca26e3a76d26c0d4f4e769eacf10fcc6 and yazi [v25.4.8](https://github.com/sxyazi/yazi/releases/tag/v25.4.8)

`~/.config/yazi/keymap.toml`

```toml
[[manager.prepend_keymap]]
on = "a"
run = "plugin augment-command -- create --open --enter"
desc = "Create a file or directory and open/enter it"
```

```
Failed to run the plugin:
runtime error: ?:-1: attempt to call a Url value (method 'parent')
stack traceback:
	?: in function <?:2728>
	(...tail calls...)
	?: in upvalue '?'
	?: in function <?:3726>
```

Maybe due to https://github.com/sxyazi/yazi/pull/2578 ? Not sure.

---

Edit: `extract` also fails

```toml
[opener]
extract = [
  { run = 'ya pub augmented-extract --list "$@"', desc = "Extract here" },
]
```

```
Failed to run the plugin:
runtime error: ?:-1: attempt to call a Url value (method 'parent')
stack traceback:
	?: in field '?'
	?: in upvalue '?'
	?: in function <?:3726>
```
