### ISSUE TITLE
shell command doesn't work when invoked in an empty directory

### ISSUE THREAD

**Issue by xfzv** [hankertrix/augment-command.yazi#16]
```console
% yazi -V
Yazi 25.5.31 (b637c32e 2025-06-05)

% kitty -v
kitty 0.41.1 created by Kovid Goyal

% lsd --tree --icon=never ~/.config/yazi
yazi
├── plugins
│   └── augment-command.yazi
│       └── main.lua
└── keymap.toml
```

I'm using the following keybinding to open a shell in the current directory:

```toml
# ~/.config/yazi/keymap.toml
[[mgr.prepend_keymap]]
on = "<Backspace>"
run = "plugin augment-command -- shell --block 'kitten run-shell kitty @ set-tab-title 'yazi terminal' ; kitty @ set-tab-title 'yazi''"
desc = "Open shell here"
```

It only works if the directory is not empty.

To reproduce (with Kitty terminal):

1. Enter a non-empty directory
2. Press `Backspace`
3. The command is executed (a shell opens, kitty tab title is set to `yazi terminal`
4. Run `exit`: back to `yazi`, the tab name is set to `yazi`

Repeat in an empty directory (no directory, no file): nothing happens when pressing `Backspace`.

Running `kitten run-shell kitty @ set-tab-title 'yazi terminal'` in an empty directory from my interactive shell (zsh) works.

Could it be because there is no hovered item in `yazi`?
