### ISSUE TITLE
`enter_archives` doesn't behave like recent upstream `yazi` improvement

### ISSUE THREAD

**Issue by xfzv** [hankertrix/augment-command.yazi#4]
```
% uname -s
Linux

% yazi -V
Yazi 0.3.3 (3e4973d 2024-09-28)
```

With the following in `~/.config/yazi/keymap.toml`:

```toml
[[manager.prepend_keymap]]
on = ["<Right>"]
run = "plugin augment-command --args='enter --no-skip'"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = ["l"]
run = "plugin augment-command --args='enter --no-skip'"
desc = "Enter the child directory, or open the file"
```

Pressing either `"<Right>"` or `"l"` on a `.tar.gz` archive doesn't behave like pressing `<Enter>` (regular `yazi` `extract`).

`extract` has been improved lately:
- original issue - https://github.com/sxyazi/yazi/issues/1548
- enhancement PR - https://github.com/sxyazi/yazi/pull/1583

Currently, `augment-command` creates the same duplicate directories that the old `extract` used to create before.

To reproduce (basically repeating steps in https://github.com/sxyazi/yazi/issues/1548): 

Using a recent `yazi` version containing https://github.com/sxyazi/yazi/pull/1583
1. Download a `tar.gz` archive
2. Hover it and press `<Enter>`: a single directory named after the `tar.gz` archive is created, with the content in it
3. Hover it and press `"<Right>"` or `"l"` with the configuration above: a `.tar` archive is created and hovered, then pressing `"<Right>` or `"l"` now hovers the directory named after the archive. Pressing `"<Right>"` or `"l"` again: the first file of the archive is finally hovered.

It would be nice if `enter_archives` could mimic the new behavior, i.e. directly extracting `.tar.gz` in a single directory and enter it.
