### ISSUE TITLE
extract command: `bad argument #1: userdata has been destructed` if using `enter --no-skip`

### ISSUE THREAD

**Issue by xfzv** [hankertrix/augment-command.yazi#8]
Linux user here. I've been trying https://github.com/hankertrix/augment-command.yazi/commit/d04ef677480bbc80be977f95fdb4f2be3ff5ea28

With the following config:

```console
~/.config/yazi
├── plugins
│   └── augment-command.yazi
│       └── init.lua
├── keymap.toml
└── yazi.toml
```

- `keymap.toml`

```toml
[[manager.prepend_keymap]]
on = ["l"]
run = "plugin augment-command --args='enter --no-skip'"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = ["<Right>"]
run = "plugin augment-command --args='enter --no-skip'"
desc = "Enter the child directory, or open the file"
```

- `yazi.toml`

```toml
[opener]
extract = [
  { run = 'ya pub augmented-extract --list "$@"', desc = "Extract here" },
]
```

1. Create an empty file:

```console
% touch test.lua
```

2. Compress it with `tar` or with `7z` (tried both, same behavior):

```console
% tar -cvf archive.tar test.lua
% 7z a archive.7z test.lua
```

3. Open `yazi`, hover `archive.tar` or `archive.7z` and press either `"l"` or `"<Right>"` to extract it
4. `yazi` task manager shows `Run micro plugin augment-command` (stuck at 99%) with the following content:

```
Micro plugin failed:
bad argument #1: userdata has been destructed
stack traceback:
	[C]: in local 'poll'
	[string "?"]:4: in field 'read_dir'
	[string "augment-command"]:1082: in upvalue 'get_directory_items'
	[string "augment-command"]:1131: in upvalue 'skip_single_child_directories'
	[string "augment-command"]:2391: in local 'command_func'
	[string "augment-command"]:3402: in upvalue 'run_command_func'
	[string "augment-command"]:3442: in function <[string "augment-command"]:3420>
```

Using `enter` without `--no-skip` or `<Enter>` (default "open" keybinding) instead works normally: the archive is extracted and there is no error.
